export const FETCH_USER = 'FETCH_USER'
export const SET_USER = 'SET_USER';
export const SET_USERS = 'SET_USERS';
export const SET_ERROR = 'SET_ERROR'
export const SET_INVOICE = 'SET_INVOICE'
export const SET_LOADING = 'SET_LOADING'
export const SET_AUTHENTICATED_ID = 'SET_AUTHENTICATED_ID'
export const SET_WITHDRAW_REQUEST = 'SET_WITHDRAW_REQUEST'

export const STOP_LOADING = 'STOP_LOADING'
export const CLEAR_ERROR = 'CLEAR_ERROR'